exports.KEYS = {};
exports.KEYS.CATEGORY_DATA = "CATEGORY_DATA";
exports.KEYS.MENU_DATA = "MENU_DATA";
exports.KEYS.CONSUMER_CARD_DETAIL = "CONSUMER_CARD_DETAIL";
exports.KEYS.LOGGED_IN_USERS_INFO = "LOGGED_IN_USERS_INFO";
exports.KEYS.CUSTOMER_ACCESS_TOKEN = "CUSTOMER_ACCESS_TOKEN";
exports.KEYS.VENDOR_ACCESS_TOKEN = "VENDOR_ACCESS_TOKEN";
exports.KEYS.CUSTOMER_SEARCH_PREF = "CUSTOMER_SEARCH_PREF";

